import type { Metadata } from "next";
import { Archivo, Doto, Geist_Mono, Metal, Noto_Sans } from "next/font/google";
import Script from "next/script";
import { SystemThemeSync } from "@/app/components/theme/SystemThemeSync";
import "./globals.css";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metal = Metal({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-metal",
  display: "swap",
});

const doto = Doto({
  subsets: ["latin"],
  variable: "--font-doto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeInit = `(function(){try{var d=window.matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.setAttribute("data-theme",d?"dark":"light");}catch(e){document.documentElement.setAttribute("data-theme","light");}})();`;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${archivo.variable} ${notoSans.variable} ${geistMono.variable} ${metal.variable} ${doto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Script id="lux-theme-init" strategy="beforeInteractive">
          {themeInit}
        </Script>
        <SystemThemeSync />
        {children}
      </body>
    </html>
  );
}
